<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>EasyDesk.Windows.Tests</AssemblyName>
    <RootNamespace>EasyDesk.Windows.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EasyDesk.Windows\EasyDesk.Windows.csproj" />
    <ProjectReference Include="..\..\src\EasyDesk.Core\EasyDesk.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>

</Project>
